Account settings  backend & frontend integration
ez4papiz1/colligo pull request #53
Opened 2024-03-11 16:00 UTC by Eneshjakhar

Changes made:
- adjusted Home page css to have better navigation bar
- changes colligo logo
- added frontend for account setttings
- added AccountSettings.css
- added AccountSettings.html

2024-03-11 16:40 UTC, ez4papiz1 approved these changes
All the changes seem correct. Should be able to merge without conflict

2024-03-11 16:40 UTC, ez4papiz1 commented on DiscordCode/FrontEnd/AccountSettings.html
Looks good

2024-03-11 16:40 UTC, ez4papiz1 commented on DiscordCode/FrontEnd/css/AccountSettings.css
Looks good

2024-03-11 16:40 UTC, ez4papiz1 commented on DiscordCode/FrontEnd/css/home.css
Looks good

2024-03-11 16:40 UTC, ez4papiz1 commented on DiscordCode/FrontEnd/images/logo.png
Looks good

2024-03-18 08:57 UTC, jordanp2002 requested changes

2024-03-18 08:57 UTC, jordanp2002 commented on DiscordCode/BackEnd/routes/AccountSettings.js
> +mongoose.connect('mongodb://localhost:27017/colligo');
Should be changed to createConnection from ".connect"

2024-03-18 08:57 UTC, jordanp2002 commented on DiscordCode/BackEnd/routes/AccountSettings.js
> +router.post('/', async (req, res) => {
Should be sending json data back so frontend can display this messages to the user.

2024-03-18 09:00 UTC, jordanp2002 commented on DiscordCode/BackEnd/routes/AccountSettings.js
> +
Should be rendering html in the route. Eg) res.render('account_settings')

2024-04-14 09:17 UTC, closed without merging