Account settings
ez4papiz1/colligo pull request #56
Opened 2024-03-11 20:58 UTC by Lunilux24

Did my best to fix the popups and forms. The buttons are not rly working in the sense that the form comes up, but it is unclosable. I feel like I am just overlooking something simple, but unfortunately i won't be able to continue working on this till tmrw at the earliest. Check it out and see if u can figure out what is wrong with the javascript. CSS can easily be implemented later.

2024-03-14 23:56 UTC, Lunilux24 commented
Pretty much completely redid the account settings to a 2 column layout with buttons on one side and information in a (temporary) white panel on the other side. There is a problem where the second column only begins where the first one ends. Not sure how to fix it, but if we add more than 3 buttons, the information window will keep moving down. Few things to fix/add here:

- Add more buttons and categories for settings.
- Add hover effect to buttons so that you can highlight them and differentiate between them.
- IMPORTANT: Fix information window to display side by side with the buttons.
- Backend for all forms.

One more thing to note, the file account_settings.html will display user info similar to how it does in the discord app. I need to add a button for it still, but it will essentially be a my account button. I've linked a picture of what the page currently looks like and what I am going for.
![Screenshot 2024-03-14 165435](https://github.com/ez4papiz1/colligo/assets/70615080/f27544c7-d83f-4f24-9fa2-74f6c4ada9d4)
![Screenshot 2024-03-14 165516](https://github.com/ez4papiz1/colligo/assets/70615080/bcb22330-7a92-40e1-a58b-73f42da6ab13)

2024-03-15 21:14 UTC, jordanp2002 commented on DiscordCode/FrontEnd/account_settings.html
> -            <script>
write javascript in seperate file under the JS folder

2024-03-15 21:15 UTC, jordanp2002 requested changes
Seperate JS into seperate files under the JS folder in the frontend directory

2024-03-15 21:47 UTC, jordanp2002 approved these changes

2024-03-15 22:22 UTC, merged